INSERT INTO tb_room_review_summary (
    room_no,
    summary_status,
    review_count,
    updated_at,
    review_summary,
    last_error_message,
    retry_count
) VALUES
('room1', 'PENDING', 0, NULL, NULL, NULL, 0),
('room2', 'PENDING', 0, NULL, NULL, NULL, 0),
('room3', 'PENDING', 0, NULL, NULL, NULL, 0),
('room4', 'PENDING', 0, NULL, NULL, NULL, 0),
('room5', 'PENDING', 0, NULL, NULL, NULL, 0),
('room6', 'PENDING', 0, NULL, NULL, NULL, 0),
('room7', 'PENDING', 0, NULL, NULL, NULL, 0),
('room8', 'PENDING', 0, NULL, NULL, NULL, 0),
('room9', 'PENDING', 0, NULL, NULL, NULL, 0),
('room10', 'PENDING', 0, NULL, NULL, NULL, 0),
('room11', 'PENDING', 0, NULL, NULL, NULL, 0),
('room12', 'PENDING', 0, NULL, NULL, NULL, 0),
('room13', 'PENDING', 0, NULL, NULL, NULL, 0),
('room14', 'PENDING', 0, NULL, NULL, NULL, 0),
('room15', 'PENDING', 0, NULL, NULL, NULL, 0),
('room16', 'PENDING', 0, NULL, NULL, NULL, 0),
('room17', 'PENDING', 0, NULL, NULL, NULL, 0),
('room18', 'PENDING', 0, NULL, NULL, NULL, 0),
('room19', 'PENDING', 0, NULL, NULL, NULL, 0),
('room20', 'PENDING', 0, NULL, NULL, NULL, 0),
('room21', 'PENDING', 0, NULL, NULL, NULL, 0),
('room22', 'PENDING', 0, NULL, NULL, NULL, 0),
('room24', 'PENDING', 0, NULL, NULL, NULL, 0),
('room25', 'PENDING', 0, NULL, NULL, NULL, 0),
('room26', 'PENDING', 0, NULL, NULL, NULL, 0),
('room27', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0001', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0002', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0003', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0004', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0005', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0006', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0007', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0008', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0009', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0010', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0011', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0012', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0013', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0014', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0015', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0016', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0017', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0018', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0019', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0020', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0021', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0022', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0023', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0024', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0025', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0026', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0027', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0028', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0029', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0030', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0031', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0032', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0033', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0034', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0035', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0036', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0037', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0038', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0039', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0040', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0041', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0042', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0043', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0044', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0045', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0046', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0047', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0048', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0050', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0052', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0053', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0054', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0055', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0057', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0058', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0059', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0060', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0061', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0062', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0063', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0064', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0065', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0066', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0067', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0068', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0069', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0070', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0071', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0072', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0074', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0075', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0076', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0077', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0078', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0079', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0080', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0081', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0082', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0083', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0085', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0086', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0087', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0088', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0091', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0093', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0094', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0095', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0096', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0097', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0098', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0099', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0100', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0101', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0102', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0103', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0104', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0105', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0106', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0107', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0108', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0109', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0110', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0111', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0112', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0113', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0114', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0115', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0116', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0118', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0120', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0121', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0122', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0123', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0124', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0125', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0126', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0127', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0128', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0129', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0130', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0131', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0132', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0133', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0134', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0135', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0136', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0137', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0138', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0139', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0140', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0141', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0142', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0143', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0144', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0145', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0146', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0147', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0148', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0149', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0150', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0151', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0152', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0153', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0154', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0155', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0156', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0157', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0158', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0159', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0160', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0161', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0162', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0163', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0164', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0165', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0166', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0167', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0168', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0169', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0170', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0171', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0172', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0173', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0174', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0175', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0177', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0178', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0179', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0180', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0181', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0182', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0183', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0184', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0185', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0186', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0187', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0188', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0189', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0190', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0191', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0192', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0193', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0194', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0195', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0196', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0197', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0198', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0199', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0201', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0202', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0203', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0204', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0205', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0206', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0208', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0209', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0213', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0214', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0215', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0216', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0217', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0218', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0219', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0220', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0222', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0223', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0224', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0225', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0226', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0227', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0228', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0229', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0230', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0231', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0232', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0234', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0235', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0236', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0237', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0238', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0239', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0240', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0241', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0242', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0243', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0244', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0245', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0246', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0247', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0248', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0250', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0251', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0252', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0254', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0255', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0256', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0257', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0258', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0259', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0260', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0261', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0262', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0263', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0264', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0265', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0266', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0267', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0268', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0269', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0270', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0271', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0272', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0273', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0274', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0275', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0276', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0277', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0278', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0279', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0280', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0281', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0282', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0283', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0284', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0285', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0286', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0287', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0288', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0289', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0290', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0291', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0292', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0293', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0294', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0295', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0296', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0297', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0298', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0299', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0300', 'PENDING', 0, NULL, NULL, NULL, 0);


INSERT INTO tb_room_image_summary (
    room_no,
    summary_status,
    image_count,
    updated_at,
    image_summary,
    last_error_message,
    retry_count
)
SELECT
    room_no,
    'PENDING',
    0,
    NULL,
    NULL,
    NULL,
    0
FROM tb_rooms_images
GROUP BY room_no;


INSERT INTO tb_room_embedding_status (
    room_no,
    embedding_status,
    updated_at,
    last_error_message,
    retry_count
)
SELECT
    r.room_no,
    'PENDING' AS embedding_status,
    NULL AS updated_at,
    NULL AS last_error_message,
    0 AS retry_count
FROM tb_rooms r
WHERE r.deleted = 0;

INSERT INTO tb_rooms_image_analysis (
    room_no,
    room_image_no,
    summary,
    caption,
    ocr_text,
    normalized_options,
    raw_json,
    analysis_created_at,
    analysis_updated_at
)
SELECT
    ri.room_no,
    ri.room_image_no,
    NULL AS summary,
    CASE MOD(ri.room_image_no, 40)
        WHEN 0 THEN '원룸 내부 전체가 보이며 침대나 책상 등을 둘 수 있는 생활 공간 중심의 사진입니다.'
        WHEN 1 THEN '방 입구 쪽에서 실내를 바라본 구도로, 전체 구조와 동선을 짐작할 수 있는 사진입니다.'
        WHEN 2 THEN '벽면과 바닥, 생활 공간 배치가 함께 보이는 기본적인 실내 전경 사진입니다.'
        WHEN 3 THEN '거주 공간의 폭과 길이를 대략 확인할 수 있는 방 내부 정면 사진입니다.'
        WHEN 4 THEN '실내 한쪽 벽면과 바닥 면적이 드러나 공간 크기를 가늠하기 쉬운 사진입니다.'
        WHEN 5 THEN '침실 겸 생활공간으로 사용할 수 있는 원룸 내부 모습이 담긴 사진입니다.'
        WHEN 6 THEN '가구 배치 전후를 상상해볼 수 있도록 방의 기본 구조가 보이는 실내 사진입니다.'
        WHEN 7 THEN '방 중앙 공간과 가장자리 구성이 함께 보여 전체적인 사용감을 짐작할 수 있는 사진입니다.'
        WHEN 8 THEN '혼자 거주하는 원룸 형태의 생활 공간 분위기를 확인할 수 있는 사진입니다.'
        WHEN 9 THEN '실내 바닥 면적과 벽면 구성이 비교적 잘 드러나는 방 내부 사진입니다.'
        WHEN 10 THEN '출입문 또는 실내 모서리 쪽에서 촬영한 듯한 구도로 공간 배치를 파악하기 쉬운 사진입니다.'
        WHEN 11 THEN '방 안 주요 생활 영역이 한눈에 들어오는 기본적인 실내 전경 사진입니다.'
        WHEN 12 THEN '침대, 수납장, 책상 등을 배치할 수 있는 공간감을 확인하기 좋은 방 사진입니다.'
        WHEN 13 THEN '원룸 특유의 단일 생활공간 구조를 살펴볼 수 있는 실내 전체 사진입니다.'
        WHEN 14 THEN '방의 넓이감과 가구 배치 여유를 대략 짐작할 수 있는 내부 모습입니다.'
        WHEN 15 THEN '생활 공간 중심으로 촬영되어 실제 거주 시 동선을 상상해볼 수 있는 사진입니다.'
        WHEN 16 THEN '벽, 바닥, 천장 일부가 함께 보이며 방 컨디션을 가볍게 확인할 수 있는 사진입니다.'
        WHEN 17 THEN '실내 구조가 단순하게 드러나 있어 원룸 배치를 이해하기 쉬운 사진입니다.'
        WHEN 18 THEN '거주 공간 한쪽에서 반대편을 바라본 형태로 방 깊이감을 느낄 수 있는 사진입니다.'
        WHEN 19 THEN '방의 기본 마감 상태와 내부 공간 활용도를 함께 볼 수 있는 실내 사진입니다.'
        WHEN 20 THEN '주 생활공간이 중심에 담겨 있어 실제 방 크기와 구조를 짐작하기 좋은 사진입니다.'
        WHEN 21 THEN '원룸 내부의 전반적인 배치와 개방감을 확인할 수 있는 기본 사진입니다.'
        WHEN 22 THEN '생활 공간 중심의 실내 모습으로, 가구를 놓았을 때의 배치를 떠올리기 쉬운 사진입니다.'
        WHEN 23 THEN '방 전체 구조와 실내 사용 면적을 대략적으로 파악할 수 있는 전경 사진입니다.'
        WHEN 24 THEN '실내 중심부가 보이는 구도로 방의 형태와 기본적인 구조를 이해하기 좋은 사진입니다.'
        WHEN 25 THEN '원룸의 생활 공간과 벽면 구성이 함께 담겨 있어 배치 구상을 해보기 쉬운 사진입니다.'
        WHEN 26 THEN '거주 공간의 기본 면적과 내부 마감 분위기를 가볍게 파악할 수 있는 사진입니다.'
        WHEN 27 THEN '방 안쪽 공간이 비교적 넓게 담겨 있어 전체적인 구조를 살펴보기 좋은 사진입니다.'
        WHEN 28 THEN '실내 전경이 중심이 되어 원룸 구조와 사용 가능한 공간을 짐작할 수 있는 사진입니다.'
        WHEN 29 THEN '가구를 배치할 수 있는 여유 공간과 방 형태를 함께 확인할 수 있는 내부 사진입니다.'
        WHEN 30 THEN '생활 공간 위주로 촬영되어 실제 거주 시 활용 모습을 떠올리기 쉬운 사진입니다.'
        WHEN 31 THEN '방의 길이감과 폭을 대략 가늠할 수 있도록 내부가 정면으로 담긴 사진입니다.'
        WHEN 32 THEN '원룸 내부 한쪽 면이 드러나 있어 수납이나 가구 배치 위치를 상상하기 좋은 사진입니다.'
        WHEN 33 THEN '실내 구조와 바닥 활용 공간을 함께 살펴볼 수 있는 기본 방 사진입니다.'
        WHEN 34 THEN '방 내부의 전반적인 크기감과 생활 동선을 짐작할 수 있는 실내 전경 사진입니다.'
        WHEN 35 THEN '혼자 거주하는 공간의 기본 형태를 보여주는 원룸 내부 사진입니다.'
        WHEN 36 THEN '벽면과 바닥 구성이 함께 보이며 실내 활용도를 파악하기 쉬운 사진입니다.'
        WHEN 37 THEN '거주 공간의 중심 영역이 담겨 있어 방 배치와 구조를 이해하기 좋은 사진입니다.'
        WHEN 38 THEN '실내 한쪽에서 전체를 바라본 느낌으로 방의 깊이와 배치를 짐작할 수 있는 사진입니다.'
        WHEN 39 THEN '방 내부 주요 공간이 한 장에 담겨 있어 전체적인 생활 공간 구조를 확인할 수 있는 사진입니다.'
    END AS caption,
    NULL AS ocr_text,
    NULL AS normalized_options,
    NULL AS raw_json,
    NOW() AS analysis_created_at,
    NULL AS analysis_updated_at
FROM tb_rooms_images ri;