

INSERT INTO tb_room_review_summary (
    room_no,
    summary_status,
    review_count,
    updated_at,
    review_summary,
    last_error_message,
    retry_count
) VALUES
('room1', 'PENDING', 0, NULL, NULL, NULL, 0),
('room2', 'PENDING', 0, NULL, NULL, NULL, 0),
('room3', 'PENDING', 0, NULL, NULL, NULL, 0),
('room4', 'PENDING', 0, NULL, NULL, NULL, 0),
('room5', 'PENDING', 0, NULL, NULL, NULL, 0),
('room6', 'PENDING', 0, NULL, NULL, NULL, 0),
('room7', 'PENDING', 0, NULL, NULL, NULL, 0),
('room8', 'PENDING', 0, NULL, NULL, NULL, 0),
('room9', 'PENDING', 0, NULL, NULL, NULL, 0),
('room10', 'PENDING', 0, NULL, NULL, NULL, 0),
('room11', 'PENDING', 0, NULL, NULL, NULL, 0),
('room12', 'PENDING', 0, NULL, NULL, NULL, 0),
('room13', 'PENDING', 0, NULL, NULL, NULL, 0),
('room14', 'PENDING', 0, NULL, NULL, NULL, 0),
('room15', 'PENDING', 0, NULL, NULL, NULL, 0),
('room16', 'PENDING', 0, NULL, NULL, NULL, 0),
('room17', 'PENDING', 0, NULL, NULL, NULL, 0),
('room18', 'PENDING', 0, NULL, NULL, NULL, 0),
('room19', 'PENDING', 0, NULL, NULL, NULL, 0),
('room20', 'PENDING', 0, NULL, NULL, NULL, 0),
('room21', 'PENDING', 0, NULL, NULL, NULL, 0),
('room22', 'PENDING', 0, NULL, NULL, NULL, 0),
('room24', 'PENDING', 0, NULL, NULL, NULL, 0),
('room25', 'PENDING', 0, NULL, NULL, NULL, 0),
('room26', 'PENDING', 0, NULL, NULL, NULL, 0),
('room27', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0001', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0002', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0003', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0004', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0005', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0006', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0007', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0008', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0009', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0010', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0011', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0012', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0013', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0014', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0015', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0016', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0017', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0018', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0019', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0020', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0021', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0022', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0023', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0024', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0025', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0026', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0027', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0028', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0029', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0030', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0031', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0032', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0033', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0034', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0035', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0036', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0037', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0038', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0039', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0040', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0041', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0042', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0043', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0044', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0045', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0046', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0047', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0048', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0050', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0052', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0053', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0054', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0055', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0057', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0058', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0059', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0060', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0061', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0062', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0063', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0064', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0065', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0066', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0067', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0068', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0069', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0070', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0071', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0072', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0074', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0075', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0076', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0077', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0078', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0079', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0080', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0081', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0082', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0083', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0085', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0086', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0087', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0088', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0091', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0093', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0094', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0095', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0096', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0097', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0098', 'PENDING', 0, NULL, NULL, NULL, 0),
('room_s0099', 'PENDING', 0, NULL, NULL, NULL, 0);


INSERT INTO tb_room_image_summary (
    room_no,
    summary_status,
    image_count,
    updated_at,
    image_summary,
    last_error_message,
    retry_count
)
SELECT DISTINCT
    room_no,
    'PENDING',
    0,
    NULL,
    NULL,
    NULL,
    0
FROM tb_rooms_images;


INSERT INTO tb_room_embedding_status (
    room_no,
    embedding_status,
    updated_at,
    last_error_message,
    retry_count
)
SELECT
    room_no,
    'PENDING',
    NULL,
    NULL,
    0
FROM tb_rooms;

INSERT INTO `tb_rooms_image_analysis` (
    `room_no`,
    `room_image_no`,
    `summary`,
    `caption`,
    `ocr_text`,
    `normalized_options`,
    `raw_json`,
    `analysis_created_at`,
    `analysis_updated_at`
)
VALUES
('room_s0001', 1, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0002', 2, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0003', 3, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0004', 4, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0005', 5, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0006', 6, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0007', 7, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0008', 8, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0009', 9, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0010', 10, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0011', 11, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0012', 12, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0013', 13, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0014', 14, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0015', 15, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0016', 16, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0017', 17, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0018', 18, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0019', 19, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0020', 20, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0021', 21, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0022', 22, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0023', 23, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0024', 24, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0025', 25, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0026', 26, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0027', 27, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0028', 28, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0029', 29, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0030', 30, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0031', 31, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0032', 32, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0033', 33, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0034', 34, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0035', 35, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0036', 36, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0037', 37, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0038', 38, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0039', 39, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0040', 40, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0041', 41, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0042', 42, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0043', 43, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0044', 44, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0045', 45, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0046', 46, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0047', 47, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0048', 48, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0049', 49, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0050', 50, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0051', 51, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0052', 52, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0053', 53, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0054', 54, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0055', 55, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0056', 56, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0057', 57, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0058', 58, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0059', 59, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0060', 60, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0061', 61, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0062', 62, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0063', 63, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0064', 64, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0065', 65, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0066', 66, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0067', 67, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0068', 68, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0069', 69, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0070', 70, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0071', 71, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0072', 72, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0073', 73, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0074', 74, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0075', 75, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0076', 76, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0077', 77, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0078', 78, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0079', 79, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0080', 80, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0081', 81, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0082', 82, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0083', 83, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0084', 84, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0085', 85, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0086', 86, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0087', 87, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0088', 88, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0089', 89, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0090', 90, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0091', 91, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0092', 92, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0093', 93, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0094', 94, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0095', 95, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0096', 96, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0097', 97, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0098', 98, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0099', 99, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0100', 100, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0101', 101, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0102', 102, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0103', 103, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0104', 104, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0105', 105, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0106', 106, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0107', 107, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0108', 108, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0109', 109, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0110', 110, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0111', 111, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0112', 112, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0113', 113, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0114', 114, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0115', 115, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0116', 116, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0117', 117, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0118', 118, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0119', 119, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0120', 120, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0121', 121, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0122', 122, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0123', 123, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0124', 124, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0125', 125, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0126', 126, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0127', 127, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0128', 128, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0129', 129, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0130', 130, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0131', 131, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0132', 132, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0133', 133, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0134', 134, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0135', 135, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0136', 136, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0137', 137, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0138', 138, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0139', 139, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0140', 140, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0141', 141, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0142', 142, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0143', 143, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0144', 144, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0145', 145, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0146', 146, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0147', 147, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0148', 148, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0149', 149, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0150', 150, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0151', 151, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0152', 152, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0153', 153, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0154', 154, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0155', 155, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0156', 156, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0157', 157, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0158', 158, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0159', 159, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0160', 160, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0161', 161, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0162', 162, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0163', 163, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0164', 164, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0165', 165, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0166', 166, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0167', 167, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0168', 168, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0169', 169, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0170', 170, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0171', 171, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0172', 172, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0173', 173, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0174', 174, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0175', 175, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0176', 176, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0177', 177, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0178', 178, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0179', 179, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0180', 180, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0181', 181, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0182', 182, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0183', 183, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0184', 184, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0185', 185, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0186', 186, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0187', 187, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0188', 188, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0189', 189, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0190', 190, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0191', 191, NULL, '채광이 들어오는 방 내부 전경을 보여주는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0192', 192, NULL, '방의 전체 구조와 내부 공간 배치를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0193', 193, NULL, '원룸 내부 모습과 주요 생활 공간이 담긴 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0194', 194, NULL, '실내 상태와 공간 활용도를 살펴볼 수 있는 방 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0195', 195, NULL, '방 내부의 분위기와 기본 구조를 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0196', 196, NULL, '생활 공간의 크기감과 배치를 파악할 수 있는 실내 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0197', 197, NULL, '방 안쪽 전경과 내부 컨디션이 잘 보이는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0198', 198, NULL, '실내 공간의 구성과 전반적인 상태를 보여주는 사진입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0199', 199, NULL, '방 구조와 가구 배치 느낌을 확인할 수 있는 이미지입니다.', NULL, NULL, NULL, NOW(), NULL),
('room_s0200', 200, NULL, '거주 공간의 전반적인 모습을 담은 방 내부 사진입니다.', NULL, NULL, NULL, NOW(), NULL);